some_string = input('Enter your string: ')
print(some_string[2])
print(some_string[-2])
print(some_string[:5])
print(some_string[:-2])
print(some_string[:: 2])
print(some_string[1::2])
print(some_string[::-1])
print(some_string[::-2])
print(len(some_string))
